### ISSUE TITLE
Support terminal and HTML markup

### ISSUE THREAD

**Issue by nichtich** [yappo/p5-String-Diff#1]
Right now one must always define `DEFAULT_MARKS` by hand which is cumbersome. For instance in every script one must write:

```
use Term::ANSIColor;

%String::Diff::DEFAULT_MARKS = ( 
    remove_open  => color('red'),
    remove_close => color('reset'),
    append_open  => color('green'),
    append_close => color('reset'),
);
```

This module should provide some default markup settings as easy options, for instance:

```
    use String::Diff qw(diff html); # sets DEFAULT_MARKS to html
    use String::Diff qw(diff ansi); # sets DEFAULT_MARKS to ansi

    diff($s1,$s2, syntax => 'html');
    diff($s1,$s2, syntax => 'ansi');
```

**Comment by yappo** [comment]
I want to reduce the dependence.
If there is a possibility, only to add to the document.

  use Term::ANSIColor;
  %String::Diff::DEFAULT_MARKS = ( 
      remove_open  => color('red'),
      remove_close => color('reset'),
      append_open  => color('green'),
      append_close => color('reset'),
  );

**Comment by nichtich** [comment]
[Term::ANSIColor](http://perldoc.perl.org/Term/ANSIColor.html) is a core module, so you don't add any additional dependency. Moreover you can just use fixed strings (also for HTML). Anyway, I use modules for not having to write the same lengthy code to every script. String::Diff should make common use cases (ANSI color markup, HTML markup) quick and simple with a single option or parameter.

**Comment by yappo** [comment]
You may need OOPish interface.

```
my $differ = String::Diff->new(
    remove_open => color('red'),
    remove_close => color('reset'),
    append_open => color('green'),
    append_close => color('reset'),
);
my $result = $differ->diff($old, $new);
```

But I'm too late response...

**Comment by renormalist** [comment]
I guess that ticket can be closed with the provided alternative usage suggestion.
